version: 3
services:
  database-api:
    image: python:3.10-slim
    volumes:
      - ./database:/app:z
    working_dir: /app
    command: './scripts/run.sh'
    environment:
      DB_URI: postgresql://postgres@db/fairyjoke-db
    ports:
      - '57302:57302'

  tracker:
    image: python:3.10-slim
    volumes:
      - ./tracker:/app:z
    working_dir: /app
    command: './scripts/run.sh'
    environment:
      DB_URI: postgresql://postgres@db/fairyjoke-tracker
    ports:
      - '57303:57303'

  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5435:5432'
    volumes:
      - /var/lib/postgresql/data
