"""init

Revision ID: 12145cd2d51a
Revises: dc1c7733d750
Create Date: 2021-12-20 05:54:29.996032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12145cd2d51a'
down_revision = 'dc1c7733d750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
