"""init ddr

Revision ID: 552c458708a6
Revises: dc1c7733d750
Create Date: 2021-12-20 08:54:34.599959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552c458708a6'
down_revision = 'dc1c7733d750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddr_musics',
    sa.Column('bpm_min', sa.Float(), nullable=True),
    sa.Column('bpm_max', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_yomigana', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('bemani', sa.Integer(), nullable=True),
    sa.Column('background_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_musics')),
    sa.UniqueConstraint('label', name=op.f('uq_ddr_musics_label'))
    )
    op.create_table('ddr_difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('playstyle', sa.Enum('SP', 'DP', name='ddrplaystyles'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('diff', sa.Enum('BEGINNER', 'BASIC', 'HARD', 'EXPERT', 'CHALLENGE', name='ddrdifficulties'), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['ddr_musics.id'], name=op.f('fk_ddr_difficulties_music_id_ddr_musics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_difficulties'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ddr_difficulties')
    op.drop_table('ddr_musics')
    # ### end Alembic commands ###
