"""sdvx init

Revision ID: 647804d4a48a
Revises: 
Create Date: 2021-12-18 08:30:30.486874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647804d4a48a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdvx_musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_yomigana', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('artist_yomigana', sa.String(), nullable=True),
    sa.Column('ascii', sa.String(), nullable=True),
    sa.Column('bpm_min', sa.Float(), nullable=True),
    sa.Column('bpm_max', sa.Float(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('background_type', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('extra_difficulty', sa.Enum('NOV', 'ADV', 'EXH', 'MXM', 'INF', 'GRV', 'HVN', 'VVD', name='difficulties'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_musics')),
    sa.UniqueConstraint('label', name=op.f('uq_sdvx_musics_label'))
    )
    op.create_table('sdvx_difficulties',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('NOV', 'ADV', 'EXH', 'MXM', 'INF', 'GRV', 'HVN', 'VVD', name='difficulties'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('effector', sa.String(), nullable=True),
    sa.Column('jacket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['sdvx_musics.id'], name=op.f('fk_sdvx_difficulties_music_id_sdvx_musics')),
    sa.PrimaryKeyConstraint('music_id', 'name', name=op.f('pk_sdvx_difficulties'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdvx_difficulties')
    op.drop_table('sdvx_musics')
    # ### end Alembic commands ###
