"""add ddr import

Revision ID: 8e0133b8afc8
Revises: 552c458708a6
Create Date: 2021-12-20 09:23:47.003797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0133b8afc8'
down_revision = '552c458708a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddr_difficulty_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_ddr_difficulty_imports_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['difficulty_id'], ['ddr_difficulties.id'], name=op.f('fk_ddr_difficulty_imports_difficulty_id_ddr_difficulties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_difficulty_imports'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ddr_difficulty_imports')
    # ### end Alembic commands ###
