"""Add sdvx genre

Revision ID: a1e81c22d12e
Revises: 5c6fb97f7add
Create Date: 2021-12-20 05:49:28.716326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e81c22d12e'
down_revision = '5c6fb97f7add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdvx_music_genres',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('Other', 'EXIT_TUNES', 'FLOOR', 'Touhou', 'Vocaloid', 'BEMANI', 'Original', 'Pop_Anime', 'Hinabita', name='genres'), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['sdvx_musics.id'], name=op.f('fk_sdvx_music_genres_music_id_sdvx_musics')),
    sa.PrimaryKeyConstraint('music_id', 'genre', name=op.f('pk_sdvx_music_genres'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort', sa.Integer(), nullable=True))

    with op.batch_alter_table('sdvx_musics', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdvx_musics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('sort')

    op.drop_table('sdvx_music_genres')
    # ### end Alembic commands ###
