"""Add sdvx music genre enum

Revision ID: bfba9e7bb8e6
Revises: 3c73ceb609ef
Create Date: 2021-12-20 04:53:55.635866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfba9e7bb8e6'
down_revision = '3c73ceb609ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
