"""init

Revision ID: dc1c7733d750
Revises: 
Create Date: 2021-12-20 05:54:22.523962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1c7733d750'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdvx_apecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('texture', sa.String(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('generator', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_apecas'))
    )
    op.create_table('sdvx_musics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_yomigana', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('artist_yomigana', sa.String(), nullable=True),
    sa.Column('ascii', sa.String(), nullable=True),
    sa.Column('bpm_min', sa.Float(), nullable=True),
    sa.Column('bpm_max', sa.Float(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('background_type', sa.Integer(), nullable=True),
    sa.Column('extra_difficulty', sa.Enum('NOV', 'ADV', 'EXH', 'MXM', 'INF', 'GRV', 'HVN', 'VVD', name='difficulties'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_musics')),
    sa.UniqueConstraint('label', name=op.f('uq_sdvx_musics_label'))
    )
    op.create_table('series',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('has_api', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('short', name=op.f('pk_series'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series'], ['series.short'], name=op.f('fk_games_series_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('short', name=op.f('uq_games_short'))
    )
    op.create_table('sdvx_difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Enum('NOV', 'ADV', 'EXH', 'MXM', 'INF', 'GRV', 'HVN', 'VVD', name='difficulties'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('effector', sa.String(), nullable=True),
    sa.Column('jacket_id', sa.Integer(), nullable=True),
    sa.Column('has_internal_jacket', sa.Boolean(), nullable=True),
    sa.Column('external_jacket', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['sdvx_musics.id'], name=op.f('fk_sdvx_difficulties_music_id_sdvx_musics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_difficulties'))
    )
    op.create_table('sdvx_music_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Enum('Other', 'EXIT_TUNES', 'FLOOR', 'Touhou', 'Vocaloid', 'BEMANI', 'Original', 'Pop_Anime', 'Hinabita', name='genres'), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['sdvx_musics.id'], name=op.f('fk_sdvx_music_genres_music_id_sdvx_musics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_music_genres'))
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_versions_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('fk_import_batches_version_id_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_table('sdvx_apeca_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apeca_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apeca_id'], ['sdvx_apecas.id'], name=op.f('fk_sdvx_apeca_imports_apeca_id_sdvx_apecas')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_sdvx_apeca_imports_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_apeca_imports'))
    )
    op.create_table('sdvx_difficulty_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_sdvx_difficulty_imports_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['difficulty_id'], ['sdvx_difficulties.id'], name=op.f('fk_sdvx_difficulty_imports_difficulty_id_sdvx_difficulties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_difficulty_imports'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdvx_difficulty_imports')
    op.drop_table('sdvx_apeca_imports')
    op.drop_table('import_batches')
    op.drop_table('versions')
    op.drop_table('sdvx_music_genres')
    op.drop_table('sdvx_difficulties')
    op.drop_table('games')
    op.drop_table('series')
    op.drop_table('sdvx_musics')
    op.drop_table('sdvx_apecas')
    # ### end Alembic commands ###
