"""add sdvx apeca

Revision ID: ee118c7d1a81
Revises: 647804d4a48a
Create Date: 2021-12-18 11:31:56.730915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee118c7d1a81'
down_revision = '647804d4a48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdvx_apecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('texture', sa.String(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('generator', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sdvx_apecas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdvx_apecas')
    # ### end Alembic commands ###
