"""init games

Revision ID: ee357e9e500e
Revises: ee118c7d1a81
Create Date: 2021-12-20 01:00:52.248858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee357e9e500e'
down_revision = 'ee118c7d1a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('has_api', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('short', name=op.f('pk_series'))
    )
    op.create_table('games',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['series'], ['series.short'], name=op.f('fk_games_series_series')),
    sa.PrimaryKeyConstraint('short', 'series', name=op.f('pk_games'))
    )
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.short'], name=op.f('fk_versions_game_games')),
    sa.ForeignKeyConstraint(['series'], ['series.short'], name=op.f('fk_versions_series_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versions')
    op.drop_table('games')
    op.drop_table('series')
    # ### end Alembic commands ###
