"""empty message

Revision ID: a5db7db00e20
Revises: e190b5eb973e
Create Date: 2022-01-03 18:44:21.977574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5db7db00e20'
down_revision = 'e190b5eb973e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddr_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_combo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ex_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clear_type', sa.Enum('fail', 'play', 'clear', 'fc', 'gfc', 'pfc', 'mfc', name='clears'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ddr_scores', schema=None) as batch_op:
        batch_op.drop_column('clear_type')
        batch_op.drop_column('ex_score')
        batch_op.drop_column('max_combo')

    # ### end Alembic commands ###
