"""init

Revision ID: e190b5eb973e
Revises: 
Create Date: 2021-12-24 03:14:54.068929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e190b5eb973e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddr_local_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('step_artist', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_local_charts'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), ),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('ddr_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('judges', sa.JSON(), nullable=True),
    sa.Column('api_chart_id', sa.Integer(), nullable=True),
    sa.Column('local_chart_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_ddr_scores_game_id_games')),
    sa.ForeignKeyConstraint(['local_chart_id'], ['ddr_local_charts.id'], name=op.f('fk_ddr_scores_local_chart_id_ddr_local_charts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ddr_scores_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_scores'))
    )
    op.create_table('ddr_score_mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('TURN', 'STEP_ZONE', 'SPEED', 'ARROW_MOVE', 'SCROLL', 'CUT', 'FREEZE_ARROW', 'JUMP', 'LIFE_GAUGE', 'SCREEN_FILTER', 'GUIDELINE'), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['ddr_scores.id'], name=op.f('fk_ddr_score_mods_score_id_ddr_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ddr_score_mods'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ddr_score_mods')
    op.drop_table('ddr_scores')
    op.drop_table('users')
    op.drop_table('games')
    op.drop_table('ddr_local_charts')
    # ### end Alembic commands ###
