"""game release datetime to date2

Revision ID: 5e9b365483be
Revises: 39ab6bebb0b1
Create Date: 2021-04-15 03:22:03.921458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9b365483be'
down_revision = '39ab6bebb0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
