"""move game group to games

Revision ID: 643edf0bf441
Revises: c1a377997522
Create Date: 2021-04-15 03:02:48.608702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643edf0bf441'
down_revision = 'c1a377997522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_group_id_game_group'), 'game_group', ['group_id'], ['id'])

    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_constraint('fk_release_group_id_game_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_release_group_id_game_group', 'game_group', ['group_id'], ['id'])

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_group_id_game_group'), type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
