"""initial db

Revision ID: f9239e9687c0
Revises: 
Create Date: 2020-08-26 00:43:12.091426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9239e9687c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_romanized', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdvx_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_yomigana', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('artist_yomigana', sa.String(), nullable=True),
    sa.Column('ascii', sa.String(), nullable=True),
    sa.Column('bpm_max', sa.Float(), nullable=True),
    sa.Column('bpm_min', sa.Float(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('demo_pri', sa.Integer(), nullable=True),
    sa.Column('extra_diff_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_romanized', sa.String(), nullable=True),
    sa.Column('name_localized', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdvx_chart',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('jacket_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('effected_by', sa.String(), nullable=True),
    sa.Column('limited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['music_id'], ['sdvx_music.id'], ),
    sa.PrimaryKeyConstraint('music_id', 'difficulty')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_romanized', sa.String(), nullable=True),
    sa.Column('title_localized', sa.String(), nullable=True),
    sa.Column('main_bpm', sa.Integer(), nullable=True),
    sa.Column('low_bpm', sa.Integer(), nullable=True),
    sa.Column('high_bpm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('sdvx_chart')
    op.drop_table('artist')
    op.drop_table('sdvx_music')
    op.drop_table('person')
    # ### end Alembic commands ###
